KodiakSite/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('crabgame/', include('crabgame.urls')),
    path('', include('crabgame.urls')),
    path('admin/', admin.site.urls),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

crabgame/urls.py
from django.urls import path
from . import views

app_name = 'crabgame'
urlpatterns = [
    path('', views.index, name='index'),
    path('image/<int:image_id>/', views.detail, name='detail'),
    path('result/<int:session_id>/', views.result, name='result'),
    path('ajax/find_oocyte/', views.find_oocyte),
    path('ajax/up_oocyte/', views.increment_oocyte),
    path('result/<int:session_id>/ajax/remove_crabs/', views.remove_crabs),
 ]

crabgame/models.py
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator
from django.utils import timezone
from django.core.files import File
import datetime
import random
import os, json
import csv
import re
import math
from sodapy import Socrata
from django.contrib.postgres.fields import ArrayField

# Create your models here.
class Crab(models.Model):
    sample_num = models.IntegerField(default = 0) # used to find the crab image
    # number of oocytes that reached more than 10 clicks
    done_oocytes = models.IntegerField(default = 0, validators = [MaxValueValidator(10)])
    year = models.IntegerField(default = datetime.date.today().year)
    latitude = models.FloatField()
    longitude = models.FloatField()
    water_temp = models.FloatField() 
    shell_condition = models.IntegerField()

    #Called by a crab when it has 10 completed oocytes. It will then send its data to socrata.
    def send_crab_data(self):
        CONVERSION_RATE = .00000701549
        oocytes = Oocyte.objects.filter(crab=self).filter(chosen_count=10)
        client = Socrata("noaa-fisheries-afsc.data.socrata.com", "q3DhSQxvyWbtq1kLPs5q7jwQp",  username="<USERNAME>", password = "<PASSWORD>")
        data = {'area_2': '',
                 'area_5': '', 
                 'calibration_5x': 0.00028, 
                 'area_4': '', 
                 'area_7': '', 
                 'area_10': '', 
                 'calibration_10x': 0.00056, 
                 'area_9': '', 
                 'year': '', 
                 'sample': '', 
                 'area_3': '', 
                 'area_8': '', 
                 'area_1': '', 
                 'area_6': ''}
        data['area_1'] = oocytes[0].area * CONVERSION_RATE
        data['area_2'] = oocytes[1].area * CONVERSION_RATE
        data['area_3'] = oocytes[2].area * CONVERSION_RATE
        data['area_4'] = oocytes[3].area * CONVERSION_RATE
        data['area_5'] = oocytes[4].area * CONVERSION_RATE
        data['area_6'] = oocytes[5].area * CONVERSION_RATE
        data['area_7'] = oocytes[6].area * CONVERSION_RATE
        data['area_8'] = oocytes[7].area * CONVERSION_RATE
        data['area_9'] = oocytes[8].area * CONVERSION_RATE
        data['area_10'] = oocytes[9].area * CONVERSION_RATE
        data['year'] = datetime.datetime.now().year
        data['sample'] = self.sample_num
        payload = [data]
        client.upsert("km2u-hwjw", payload)


    #creates a new crab, finds all of its images and adds them to the system
    #also imports oocyte instances for each image
    #find path, for each folder, create crab, read its data from socrata, read all the images on that path
    @classmethod
    def create_image_instances(cls, path):
        print(path)
        for root, dirs, files in os.walk(path, topdown=False):
            for folder in dirs:
                sn = int(folder)
                #If the crab is not already in the system, then create it
                if(Crab.objects.filter(sample_num = sn).count() == 0):
                    client = Socrata("noaa-fisheries-afsc.data.socrata.com", "q3DhSQxvyWbtq1kLPs5q7jwQp",   username="<USERNAME>", password = "<PASSWORD>")
                    crab_info = client.get("n49y-v5db", where=("sample = " + str(sn)))
                    lat, lon = crab_info[0]['location_1']['latitude'], crab_info[0]['location_1']['longitude']
                    yr, wt = crab_info[0]['year'], crab_info[0]['bottom_temp_c']
                    sc = crab_info[0]['shell_condition']
                    crab = Crab(sample_num=sn, year=yr, longitude=lon, latitude=lat, water_temp = wt, shell_condition = sc)
                
                
                    #This path would be where all the images are stored locally before upload
                    #Python script should be pushing images to this path along with its csv file
                    if(path[-1:] == '/'):
                        image_folder = path + str(sn)
                    else:
                        image_folder = path + '/' + str(sn)
                    crab.save()

                    for filename in os.listdir(image_folder):
                        #look for a resized image and then find its labeled counterpart
                        if(filename[-12:] == "_resized.png"):
                            #tag is the identifier for that image
                            tag = filename[:-12]
                            
                            #open both original and resized
                            orig = File(open(image_folder + '/' + tag + '_resized.png', 'rb'))
                            label = File(open(image_folder + '/' + tag + '_labeled.png', 'rb'))

                            data = tag + "_area.csv"

                            #create Image instance and save images to the media root directory
                            image = Image(crab=crab, csv = data)
                            image.original_img.save(tag + "_resize.png", orig, save=False)
                            image.binarized_img.save(tag + "_label.png", label, save=False)
                            image.save()

                            #read csv for image and import new oocyte instances
                            #csv must be located in the original path directory where the images were stored
                            with open(image_folder + '/' + data, 'r', newline='') as csvfile:
                                areareader = csv.reader(csvfile, delimiter = ',', quotechar = '|')
                                for row in areareader:
                                    area, xcenter, ycenter = row[0], row[1], row[2]
                                    Oocyte.objects.create(crab=crab, image = image, area = area, center_x = xcenter, center_y = ycenter)

    def __str__(self):
        return ("crab (pk=" + str(self.id) + ", sample_num=" + str(self.sample_num) + ")")
        #return str((self.sample_num, self.done_oocytes, self.year, self.longitude, self.latitude, self.water_temp))

def get_upload_path(instance, filename):
    return '{0}/{1}'.format(instance.crab.sample_num, filename)

class Image(models.Model):
    crab = models.ForeignKey(Crab, on_delete = models.CASCADE) # when crab is deleted, images are deleted
    # path of the original and binarized image
    original_img = models.ImageField(upload_to=get_upload_path)
    binarized_img = models.ImageField(upload_to=get_upload_path)
    # string of the csv file name
    csv = models.CharField(max_length = 100)

    def get_img_num(self):
        # example file name: '63/untitled014_resize.png'
        file = self.original_img.name
        # example halfname: '014_resize.png'
        halfname = file.split("untitled")[1]
        # example num: 014
        num = halfname.split("_")[0]
        return num

    def __str__(self):
        return ("image (pk=" + str(self.id) + ")")

    #Given a click position, finds which of an image's
    #oocytes are closest and returns that oocyte
    def find_closest_oocyte(self, xclick, yclick):
        oocytes = Oocyte.objects.filter(image=self.id)
        pt = (float(xclick),float(yclick))
        min_dist = -1
        mindex = -1
        for idx, oocyte in enumerate(oocytes):
            oocyte_center = (oocyte.center_x, oocyte.center_y)
            dist = distance(pt, oocyte_center)
            if(dist < min_dist or min_dist == -1):
                min_dist = dist
                mindex = idx
        return oocytes[mindex]

def distance(p0, p1):
    return math.sqrt((p0[0] - p1[0])**2 + (p0[1] - p1[1])**2)

class Oocyte(models.Model):
    crab = models.ForeignKey(Crab, on_delete = models.CASCADE)
    image = models.ForeignKey(Image, on_delete = models.CASCADE)
    chosen_count = models.IntegerField(default = 0) # how many times an oocyte has been clicked by others
    area = models.IntegerField()
    center_x = models.FloatField()
    center_y = models.FloatField()

    def __str__(self):
        return ("oocyte (pk=" + str(self.id) + ")")

    # method to increment chosen_count each time somebody clicks on a particular oocyte
    def increment_chosen_count(self):
        self.chosen_count+=1
        self.save()
        if(self.chosen_count == 10):
            self.crab.done_oocytes += 1
            self.crab.save()
            if(self.crab.done_oocytes >= 10):
                self.crab.send_crab_data()
    # method to call Crab model to increment done_oocyte once chosen_count reaches desired accuracy 

    # method to check if done_oocyte already incremented once for this instance of Oocyte, 
    # then increment chosen_count but not done_oocyte


class PlaySession(models.Model):
    num_photos = models.IntegerField(default = 8) # assume 12 photos per game session for now
    # photos = ArrayField(max_length = num_photos)
    completed_photos = models.IntegerField(default = 0)

    # method to end PlaySession when completed_photos is incremented to equal num_photos
    #global photos
    # method to increment completed_photos
    def __str__(self):
        return ("playSession (pk=" + str(self.id) + ")")

    # create a list of 12 photos with random images for user to play when PlaySession instance is created
    def setPhotos(self):
        allCrabs = list(Crab.objects.all())
        crabList = random.sample(allCrabs, min(10, len(allCrabs))) # pick 4 random crabs per PlaySession 
        
        photos = []
        for i in range (0, len(crabList)):
            images = list(crabList[i].image_set.all()) # look at all images from one crab of crabList
            playImg = random.sample(images, min(2, len(images))) # pick at most 2 random images from each crab
            for j in range (0, len(playImg)):
                photos.append(playImg[j])
                psi = PlaySessionImage(image = playImg[j], session = self)
                psi.save()
        return photos
    
    def getCrabs(self):
        analyzedCrabs = []

crabgame/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import Crab, Image, Oocyte,  PlaySession
import random
import json

# Create your views here.

# if start start button or play again clicked, create instance of PlaySession and get 12 random photos to play 
def index(request):
    if request.method == 'POST':
        playSessionInstance = PlaySession()
        playSessionInstance.save()
        photos = playSessionInstance.setPhotos()
        total = len(photos)
        print("Total = " + str(total))
        return render(request, 'crabgame/playCrabImg.html', {'photos': enumerate(photos), 'total': total, 'session_id': playSessionInstance.id})
    return render(request, 'crabgame/index.html')

#Gets data from ajax request, finds oocyte clicked,
#and passes this back as a JSON response
def find_oocyte(request):
    x, y = request.GET.get('xclick'), request.GET.get('yclick')
    photoid = request.GET.get('photoid')
    photo = Image.objects.get(pk=photoid)
    clicked_oocyte = photo.find_closest_oocyte(x, y)
    resp = { 'xcenter': clicked_oocyte.center_x, 'ycenter': clicked_oocyte.center_y, 'id': clicked_oocyte.id }
    return HttpResponse(json.dumps(resp), content_type="application/json")

def increment_oocyte(request):
    oocyte_id = request.GET.get('id')
    Oocyte.objects.get(pk=oocyte_id).increment_chosen_count()
    return HttpResponse()
     
# view the image of a certain crab and click on the oocytes in the image
def detail(request, image_id):
    photo = Image.objects.get(pk=image_id)
    return render(request, 'crabgame/detail.html', {'photo':photo})

# display the result page after the user have completed a session
def result(request, session_id):
    # if click play again button on results page, start new play session
    if request.method == 'POST':
        playSessionInstance = PlaySession()
        playSessionInstance.save()
        photos = playSessionInstance.setPhotos()
        total = len(photos)
        return render(request, 'crabgame/playCrabImg.html', {'photos': enumerate(photos), 'total': total, 'session_id': playSessionInstance.id})
    session = PlaySession.objects.get(pk=session_id)
    analyzedCrabs = session.getCrabs()
    crabCount = len(analyzedCrabs)
    return render(request, 'crabgame/result.html', {'analyzedCrabs': enumerate(analyzedCrabs), 'crabCount': crabCount})

# Remove crabs that have reached done_oocytes count 
def remove_crabs(request, session_id):
    crab_ids = request.GET.get('crab_ids')
    crab_ids = set(crab_ids.split(","))
    for elem in crab_ids:
        crab_id = int(elem)
        crab = Crab.objects.get(pk=crab_id)
        print("The crab pk is " + str(crab_id))
        if crab.done_oocytes >= 10:
            crab.delete()
    return HttpResponse()

crabgame/templates/crabgame/detail.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
  <meta name="viewport" content="width=device-width, initial-scale=1"/>
  <title>Kodiak Crab Game</title>

  <!-- CSS  -->
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <link href="{% static 'crabgame/css/materialize.css' %}" type="text/css" rel="stylesheet" media="screen,projection"/>
  <link href="{% static 'crabgame/css/style.css' %}" type="text/css" rel="stylesheet" media="screen,projection"/>
</head>

<body>
<nav class="white" role="navigation">
    <div class="nav-wrapper container">
      <a id="logo-container" href="{% url 'crabgame:index' %}" class="brand-logo">Kodiak-Crab</a>
      <ul class="right hide-on-med-and-down">
        <li><a href="#">About Us</a></li>
      </ul>
      <ul id="nav-mobile" class="sidenav">
        <li><a href="#">About Us</a></li>
      </ul>
      <a href="#" data-target="nav-mobile" class="sidenav-trigger"><i class="material-icons">menu</i></a>
    </div>
  </nav>
  <br><br>

    <div class="row">
      <div class="col s6 m6 l6">
        <img id="original" src="/media/{{ photo.crab.sample_num }}/untitled{{ photo.get_img_num }}_resize.png"/>
      </div>
      <div class="col s6 m6 l6">
        <img id="binarized" src="/media/{{ photo.crab.sample_num }}/untitled{{ photo.get_img_num }}_label.png"/>
      </div>
    </div>
    <a class="waves-effect waves-light btn" id="next">Next</a>
    <!--  Scripts-->
  <script src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
  <script src="{% static 'crabgame/js/materialize.js' %}"></script>
  <script src="{% static 'crabgame/js/init.js' %}"></script>
</body>
</html>

crabgame/templates/crabgame/index.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
  <!-- CSS  -->
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Roboto+Slab|Noto+Serif" rel="stylesheet">
  <link href="{% static 'crabgame/css/materialize.css' %}" type="text/css" rel="stylesheet" media="screen,projection"/>
  <link href="{% static 'crabgame/css/style.css' %}" type="text/css" rel="stylesheet" media="screen,projection"/>

  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0"/>
  <title>Crab 'n Click</title>
</head>

<body>
  <nav class="cyan darken-2" role="navigation">
    <div class="nav-wrapper container" id="nav-content">
      <a id="logo-container" href="{% url 'crabgame:index' %}" class="brand-logo"><img src="{% static 'crabgame/img/logo.png' %}" id="logo"/></a>
      <ul class="right hide-on-med-and-down">
        <li><a href="http://www.noaa.gov" target="_blank">
          <img src="{% static 'crabgame/img/noaalogo.jpg' %}" id="noaalogo" height=110/></a>
        </li>
        <li><a href="https://www.kibsd.org" target="_blank">
          <img src="{% static 'crabgame/img/KIBSDlogo.png' %}" id="noaalogo" height=110/></a>
        </li>
        <li>
          <a href="{% url 'admin:index' %}" target="_blank" id="adminlogin" class="waves-effect waves-light btn deep-orange lighten-1">Login Admin</a>
          <a href="https://noaa-fisheries-afsc.data.socrata.com/login" target="_blank" id="socratalogin" class="waves-effect waves-light btn deep-orange lighten-1">Login Socrata</a>
        </li>
      </ul>
    </div>
  </nav>

  <div id="startScreen" class="cyan darken-3">
    <div class="row center" id="intro">
        <h4 class="header col s12 light" style="line-height: 1.6">Help the NOAA Kodiak Lab and Shellfish Assessment Program analyze crabs collected from the Bering Sea</h4>
    </div>
    <br><br><br><br><br><br>
    <div class="row center">
        <!-- when button clicked, trigger function to create instance of a PlaySession -->
        <form method="post" action="">{% csrf_token %}
          <button id="startBtn" class="btn-large waves-effect deep-orange lighten-1" type="submit">Get Started</button>
        </form>
    </div>
    <br><br>
  </div>

  <div class="teal lighten-5">
  <br><br>
  <div id="content" class="teal lighten-5">

    <div id="about" class="row">
      <div id="aboutGame">
          <div class="row">
            <div class="col s6">
              <h4 class="center">About Crab 'n Click</h4>
              <p class="light">The Kodiak Lab is part of NOAA’s Shellfish Assessment Program, which seeks to assess the distribution and abundance of commercially important crab and groundfish resources in the eastern Bering Sea. Each year, the Kodiak Lab goes out to sea and brings back 400-800 crabs. One way to determine if a crab is going to mate each year is to analyze its oocytes - the female reproductive cells before they are fertilized. With global warming and climate change, the reproductive systems of these snow crabs have become inconsistent. Help the Kodiak Lab researchers analyze these crab's oocytes so they can locate productive fishing grounds and help Crab Fisheries Management regulate takes to improve the overall viability of future crab stocks.</p>
              <br>
              <p class="light">Learn more about the <a href="https://www.afsc.noaa.gov/Kodiak/kodiakLab_HOME.php" target="_blank">Kodiak Lab</a> or the <a href="https://www.afsc.noaa.gov/RACE/shellfish/shellfish_HOME.php" target="_blank">Shellfish Assessment Program.</a></p>
            </div>
            <div class="col s6">
                <br><br><br>
                <img id="img1" src="{% static 'crabgame/img/img1.jpg' %}" height=330 />
            </div>
          </div>

          <div class="row">
            <div class="col s6">
                <img id="img3" src="{% static 'crabgame/img/img3.jpg' %}" height=330 />
            </div>
            <div class="col s6">
                <img id="img2" src="{% static 'crabgame/img/img2.jpg' %}" height=330 />
            </div>
          </div>
          <br>
      </div>
    </div>
  </div> 
  <br><br>
  </div>

  <footer class="page-footer cyan darken-2">
      <div class="row cyan darken-2" id="contactRow">
        <div class="col l6 s12">
        <div id="creators">
          <h5 class="white-text">The Creators</h5>
          <p class="grey-text text-lighten-4">
              This game was made by a 67-373 student team within the Carnegie Mellon University Information Systems Program. 
              67-373 is an IS Consulting Project course where students have 13 weeks to consult with a client to design, 
              build, and deliver a technology solution which meets their needs. 
          </p>
        </div>
        </div>

        <div class="col l3 s12">
        <div id="contactNames">
          <h5 class="white-text">Contact Us</h5>
          <ul>
            <li>Connor Fitzgibbon</li>
            <li>Hera Miao</li>
            <li>Rich Zhu</li>
            <br>
            <li><a class="white-text" href="https://www.cmu.edu" target="_blank">Carnegie Mellon University </a></li>
            <li><a class="white-text" href="https://www.cmu.edu/information-systems/" target="_blank">CMU IS Program</a></li>
          </ul>
        </div>
        </div>

        <div class="col l3 s12">
        <div id="contactEmail">
        <br><br>
          <ul>
            <li><a class="white-text" href="mailto:cfitzgib@andrew.cmu.edu">cfitzgib@andrew.cmu.edu</a></li>
            <li><a class="white-text" href="mailto:heram@andrew.cmu.edu">heram@andrew.cmu.edu</a></li>
            <li><a class="white-text" href="mailto:ruiquzhu@andrew.cmu.edu">ruiquzhu@andrew.cmu.edu</a></li>
          </ul>
        </div>
        </div>
      </div>

  </footer>

  <!--  Scripts-->
  <script src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
  <script src="{% static 'crabgame/js/materialize.js' %}"></script>
  <script src="{% static 'crabgame/js/init.js' %}"></script>

  </body>
</html>

crabgame/templates/crabgame/playCrabImg.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
  <meta name="viewport" content="width=device-width, initial-scale=1"/>
  <title>Crab 'n Click</title>

  <!-- CSS  -->
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <link href="{% static 'crabgame/css/materialize.css' %}" type="text/css" rel="stylesheet" media="screen,projection"/>
  <link href="{% static 'crabgame/css/style.css' %}" type="text/css" rel="stylesheet" media="screen,projection"/>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
  <script src="{% static 'crabgame/js/javascript.js' %}"></script>
</head>

<body>

  <!-- Navigation Bar -->
  <nav class="cyan darken-2" role="navigation">
    <div class="nav-wrapper container" id="nav-content">
      <a id="logo-container" href="{% url 'crabgame:index' %}" class="brand-logo"><img src="{% static 'crabgame/img/logo.png' %}" id="logo"/></a>
      <ul class="right hide-on-med-and-down">
        <li><a href="http://www.noaa.gov" target="_blank">
          <img src="{% static 'crabgame/img/noaalogo.jpg' %}" id="noaalogo" height=110/></a>
        </li>
        <li><a href="https://www.kibsd.org" target="_blank">
          <img src="{% static 'crabgame/img/KIBSDlogo.png' %}" id="noaalogo" height=110/></a>
        </li>
      </ul>
    </div>
  </nav>

  <div id="playImg" class="teal lighten-5">
    <!-- Display images of crabs --> 
    {% for idx, photo in photos %}
      <div class="row" id="image{{idx}}">
        <div class = "row">
          <h4>Image {{ idx|add:"1" }}/{{ total }}</h4>
        </div>
        <div class = "row">
          <a class="modal-trigger" href="#modal">
              <i class="small material-icons" style="font-size:40px">help_outline</i>
          </a>
        </div>
        <div class = "row">
          <div class="col s6 m6 l6">
            <img id="original" src="/media/{{ photo.crab.sample_num }}/untitled{{ photo.get_img_num }}_resize.png"/>
          </div>
          <div class="col s6 m6 l6">
            <img id="binarized{{idx}}" src="/media/{{ photo.crab.sample_num }}/untitled{{ photo.get_img_num }}_label.png"/>
          </div>
          <input type="hidden" id= "img{{idx}}" name="{{photo.pk}}" value="{{ photo.pk }}" >
        </div>
        {% if idx < total|add:"-1" %}
          <a class="waves-effect waves-light btn deep-orange lighten-1" id="next" onclick= "nextImg()">Next</a>
        {% else %}
          <a class="waves-effect waves-light btn deep-orange lighten-1" id="submit" href="{% url 'crabgame:result' session_id %}" >Submit</a>
        {% endif %}
      </div>

    {% endfor %}

  </div>
  <input type = "hidden" id= "total_images" value = "{{ total }}">

  <!-- Modal Pop Up Instructions -->
  <div id="modal" class="modal">
      <div class="modal-content">
        <h5>How to Play:</h5>
        <p>
          Identify and click on all of the <b>good oocytes</b> on the labeled image on the right side.  
          Looking at the original, microscope image on the left, a good oocyte is one that is both 
          <b>dark and mostly circular</b>. Once a good ocyte on the left has been identified, 
          click on the corresponding oocyte on the right side image to mark it. 
        </p>
        <p>
          * There can be anywhere between <b>0-8</b> good oocytes in one image
        </p>
        <p>
          * Oocytes cut off on the side of images are <b>NOT good oocytes</b>
        </p>
        <p>
          * If 2 oocytes touching are the same color, they are connected and are <b>NOT good oocytes</b>
        </p>
        <p><b>Ex. Good Oocytes</b></p>
        <img src="{% static 'crabgame/img/goodOrig.png' %}" width=140 height=150 />
        <img src="{% static 'crabgame/img/goodBin.png' %}" width=140 height=150 />
        <img src="{% static 'crabgame/img/goodOrig2.png' %}" width=140 height=150 />
        <img src="{% static 'crabgame/img/goodBin2.png' %}" width=140 height=150 />
        <p><b>Ex. Bad Oocytes</b></p>
        <img src="{% static 'crabgame/img/badOrig2.png' %}" width=140 height=150 />
        <img src="{% static 'crabgame/img/badBin2.png' %}" width=140 height=150 />
        <img src="{% static 'crabgame/img/badOrig.png' %}" width=140 height=150 />
        <img src="{% static 'crabgame/img/badBin.png' %}" width=140 height=150 />
      </div>
      <div class="modal-footer">
        <a href="#!" class="modal-action modal-close waves-effect waves-light btn deep-orange lighten-1">Play Game</a>
      </div>
  </div>


  <!--  Scripts -->
  <script src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
  <script src="{% static 'crabgame/js/materialize.js' %}"></script>
  <script src="{% static 'crabgame/js/init.js' %}"></script>

  <script>
      $(document).ready(function(){
          $('.modal').modal();
          $('#modal').modal('open');
      });
  </script>

</body>

</html>

crabgame/templates/crabgame/playImg.html
<!DOCTYPE html>
<html>

<head>

<body>

<h1>You are looking at image {{ displayImg.pk }} of crab {{ displayImg.crab.sample_num }}</h1>
<img src="/media/{{ displayImg.crab.sample_num }}/original1.png"/>
<img src="/media/{{ displayImg.crab.sample_num }}/binarized1.png"/>


</body>

</head>

</html>